name: "cd"

on:
  push:
    branches:
      - main

jobs:
  Publish:
    name: Auto version bump and publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4

      - name: Use Node.js v20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'

      - name: Install Dependencies
        run: yarn install

      - name: Building the app
        run: yarn run build

      - name: Bump Version
        run: |
          # Automatically bump patch version
          yarn version patch --no-git-tag-version

          # Get the new version
          NEW_VERSION=$(node -p "require('./package.json').version")
          echo "NEW_VERSION=${NEW_VERSION}" >> $GITHUB_ENV
          echo "New version: ${NEW_VERSION}"

      - name: Commit Version Change
        run: |
          git add package.json
          git commit -m "chore: bump version to v${{ env.NEW_VERSION }} [skip ci]"
          git push

      - name: Create Git Tag
        run: |
          git tag "v${{ env.NEW_VERSION }}"
          git push origin "v${{ env.NEW_VERSION }}"

      - name: Publish to NPM
        run: |
          yarn publish --access public --non-interactive --new-version ${{ env.NEW_VERSION }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
