name: "npm-release"

on:
  release:
    types:
      - published

jobs:
  Publish:
    name: update on new release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4

      - name: Install Node v20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org

      - name: Install Dependencies
        run: yarn install

      - name: Building the app
        run: yarn build

      - name: Bump Version & Publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
        run: |
          echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" > .npmrc
          pnpm publish --access public --no-git-checks

